### PR TITLE
Fixed drag zoom inaccuracy

### PR DESCRIPTION
**Pull request by Skuhoo**
I've added an offset to the two start points and two end points associated with drag zooming. This fixes any inaccuracy with drag zooming.
Here's a jsfiddle with the fixes implemented: https://jsfiddle.net/27czaj4o/

I apologize if I've done something wrong. I'm new to this whole git thing.

### CODE REVIEW

**Comment by etimberg** [comment]
Thanks @Skuhoo 
Is it possible to post a jsfiddle that has these fixes that I could try quickly?

**Comment by Skuhoo** [comment]
I've updated my original comment with a link to a jsfiddle @etimberg

**Comment by niutski** [comment]
I'd love to see this fixed in the near future :)

**Comment by etimberg** [comment]
I can merge this.

@Skuhoo can you fix the merge conflict?

**Comment by Skuhoo** [comment]
@etimberg 
I still have no idea how git works so I can't fix whatever merge conflict there is. I'm just gonna close this pull request and let someone else do it. It's a simple fix so anyone is free to just look at what I changed and create their own pull request.

**Comment by niutski** [comment]
I'll make another pull request with the fix.

**Pull request closed without merging**
